name: Continuous Deployment Android

on:
  push:
    branches: [development]
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  APK_FILENAME: Squads

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: Squads.apk
          path: app/release/app-release.apk
  release_apk:
    name: Release APK
    needs: [apk]
    runs-on: ubuntu-latest
    steps:
      # Download Signed APK
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.APK_FILENAME }}.apk # done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # TODO
        with:
          tag_name: v0.${{ github.run_number }}
          release_name: Release v0.${{ github.run_number }}

      - name: Upload Signed APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # TODO
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APK_FILENAME }}.apk # Done
          asset_name: ${{ env.APK_FILENAME }}.apk # Done
          asset_content_type: application/zip
