name: Continuous Deployment Android
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  APK_FILENAME: Squads

jobs:
  apk:
    name: Generate APK
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleRelease

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: Squads.apk
          path: app/release/app-release.apk
      - name: Release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: signedReleaseFile
        uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
  upload:
    needs: [apk]
    name: Upload the signed artifact
    runs-on: ubuntu-latest
    steps:
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: signed_app_bundle
          path: /Squads.apk
  remove-old-artifacts:
    runs-on: ubuntu-latest
    # timeout-minutes: 10
    permissions: write-all

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "10 seconds" # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          # skip-tags: true
          skip-recent: 2
